### ISSUE TITLE
Add search trip by name

### ISSUE THREAD

**Issue by jtraweek** [jtraweek/690#19]

**Comment by WJPierro** [comment]
I implemented the change in commit 480aeb727219e2b92863fcee528054620983b99d.

The itinerary/discover unit tests in test_views were split to test search by trip title and search by trip location separately.

The search code in views._render_itineraries was updated to look for a partial match of trip title as well as trip location.

I ran the unit tests to confirm the changes work.

Assigning to @jtraweek  to review the changes.
