### ISSUE TITLE
Compile list of last Semester's features

### ISSUE THREAD

**Issue by WJPierro** [jtraweek/690#26]
We need a list of the features that the webapp had at the end of the 2017 Spring Semester. We have a tag at https://github.com/jtraweek/690/tree/baseline-20170913 which covers where we left off last Semester.

**Comment by jtraweek** [comment]
Created a PowerPoint that included all application code information, features, and webpage designs. Emailed it to professor and group members' Stevens emails on 10/10. Will upload to Google docs folder as well.
