### ISSUE TITLE
Create Backend for User Account info

### ISSUE THREAD

**Issue by jtraweek** [jtraweek/690#27]
Create form that will allow us to edit user's username, password, email, and bio

**Comment by WJPierro** [comment]
I created two views: one for editing the user profile info (username, email, bio) and one for changing the password.

We should have a form to let the user upload an avatar picture too.

Commits:
Edit Profile page: 9de24c4a4c3e6d0b233033d13054be890bca60bf
Change Password page: 0730b0a82d95a6b1872bf24e55f56ff2ee4c2f9c
Unit tests for Edit Profile: c6c09b2b970866a102eddb8c989ee0bc10d1dbee
Unit tests for Change Password: abfbfed37c3b32fd42c5fd8884dd904cf92e27fe

**Comment by WJPierro** [comment]
Added avatar upload field to the edit profile page. It could probably still use some stylizing.

Commit: 6b46d657e441551e5034444397845efc8a51d195

**Comment by WJPierro** [comment]
This is issue can be closed.

**Comment by WJPierro** [comment]
This issue can be closed.
