### ISSUE TITLE
Clean up technical debt

### ISSUE THREAD

**Issue by jtraweek** [jtraweek/690#8]

**Comment by WJPierro** [comment]
I had to update the requirements.txt file as some dependencies were still missing. Commits: 2bd9e92140b702f52922daed5084378606b3590b and 8f3ac9e3a3ffaa7cc43494f193992a161f848a3a

This forked repository was not up-to-date with latest version of the upstream repository. Had to merge the later changes. Commits: a3bc68203c777ef5bb79975c1c89eabcf3f4be80 and 7993ba1029703e2bac69d594ee15296b5c9dc959

**Comment by WJPierro** [comment]
All the views were tested in one unit test class in views.py. I split it into separate classes for readability and maintainability. Commit: 8062d73f8e9fc0729d0e6febd9d9a31dfab8487d

Removed some duplicate tests: 245cd2c6c684a8851e72d4e2581377f816a2d654

**Comment by WJPierro** [comment]
Added database migration capabilities. We may or may not use them. Commit: 62830294fd07485d1df0e8c3b45f1d88948ab78b

**Comment by WJPierro** [comment]
Added a CRUDMixin class to models.py for easier create/read/update/delete functionality for database models. Commit: c9ade3fd95f93b62dfbc0053dcd2a7dd86461d21

**Comment by WJPierro** [comment]
We may able to close this now. Assigning to @jtraweek to review. Also might want the rest of the team to review.
